#!/usr/bin/env bash
# Assemble the Jekyll source from docs/ (regenerated by the release exporter,
# so it cannot carry site config) and site/ (this repository's own).
set -euo pipefail

SRC=${1:-_site_src}
rm -rf "$SRC"
mkdir -p "$SRC"
cp -R docs/. "$SRC"/
cp -R site/. "$SRC"/
rm -f "$SRC"/README.md "$SRC"/build.sh "$SRC"/swap_hero.py "$SRC"/prepare_pages.py

# Use this repository's hero on the front page instead of the exporter's chosen
# example. Fails the build if the export drifts, rather than silently keeping
# the old one.
./site/swap_hero.py "$SRC"

# Front matter, .md -> .html links, and the empty table headers.
./site/prepare_pages.py "$SRC"
