#!/usr/bin/env bash
# Assemble the Jekyll source from docs/ (regenerated by the release exporter,
# so it cannot carry site config) and site/ (this repository's own).
set -euo pipefail

SRC=${1:-_site_src}
rm -rf "$SRC"
mkdir -p "$SRC"
cp -R docs/. "$SRC"/
cp -R site/. "$SRC"/
rm -f "$SRC"/README.md "$SRC"/build.sh

# The exporter writes plain markdown with no YAML front matter. Jekyll treats a
# front-matter-less file as a static file and copies it through untouched, so
# without this the site serves raw .md and has no index.html at all.
find "$SRC" -name '*.md' -print0 | while IFS= read -r -d '' f; do
  head -n 1 "$f" | grep -qx -- '---' && continue
  title=$(grep -m1 '^# ' "$f" | sed 's/^# //' || true)
  { printf -- '---\nlayout: default\n'
    [ -n "$title" ] && printf 'title: %s\n' "$(printf '%s' "$title" | sed 's/"/\\"/g')"
    printf -- '---\n'
    cat "$f"
  } > "$f.tmp"
  mv "$f.tmp" "$f"
done

# Relative links between the pages point at .md. GitHub Pages' own build enables
# jekyll-relative-links, which rewrites them, but doing it here keeps the site
# correct under a plain `jekyll build` too.
find "$SRC" -name '*.md' -print0 | while IFS= read -r -d '' f; do
  sed -i -E 's/\]\(([^):]*)\.md(#[^)]*)?\)/](\1.html\2)/g' "$f"
done
