#!/usr/bin/env python3
"""Replace the manual's front-page hero with the repository's own.

docs/ is regenerated by the release exporter, so the hero there is whichever
example the exporter picked. This swaps it at build time for assets/, which
this repository controls.

Both the image and its caption must be replaced together: the exporter's
caption says the diagram ships with the app, which is true of the example and
false of ours. If either pattern stops matching -- the exporter changed the
example, the wording or the markup -- this exits non-zero rather than leaving a
half-swapped page or quietly publishing the old hero. A failed build is
visible; a silent revert is not.
"""

import pathlib
import re
import shutil
import sys

HERO = "assets/Diagram_Hero.svg"
ALT = ("A fibre link stabilised over 15 km, drawn in Quickdraw: the optics, "
       "the RF chain and the FPGA servo in one diagram")
CAPTION = ("*A fibre link stabilised over 15 km — the optics, the RF chain and the\n"
           "FPGA servo in one diagram, exported straight to SVG.*")

# The exporter writes the hero as an <img> at an example under
# generated/examples/, followed by an italic caption paragraph.
IMG = re.compile(r'<img src="generated/examples/[^"]+\.svg"[^>]*>')
CAP = re.compile(r'^\*`[^`]+\.dsd`, one of the examples that ships with the app:'
                 r'.*?\*$', re.DOTALL | re.MULTILINE)


def fail(msg):
    sys.exit(
        "swap_hero: %s\n"
        "  The manual's front page no longer looks the way this script expects,\n"
        "  so the hero was not swapped. Update site/swap_hero.py to match the\n"
        "  current export, or drop the call to it from site/build.sh." % msg)


def main():
    src = pathlib.Path(sys.argv[1])
    index = src / "index.md"
    text = index.read_text()

    if not IMG.search(text):
        fail("no example hero <img> found in index.md")
    if not CAP.search(text):
        fail("the hero caption in index.md did not match")

    text = IMG.sub('<img src="%s" alt="%s" width="820">' % (HERO, ALT), text, count=1)
    text = CAP.sub(CAPTION, text, count=1)
    index.write_text(text)

    shutil.copy(HERO, src / "assets" / pathlib.Path(HERO).name)


if __name__ == "__main__":
    main()
